name: Data

on:
  push:
    paths:
      - 'data/**'
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.0.0
      - name: Install dependencies
        run: npm ci
      - name: Compress data
        run: npm run data:compress
      - name: Format data
        run: npm run data:format
      - name: Format repository data
        uses: EndBug/add-and-commit@v4
        with:
          author_name: Kalle Ilves
          author_email: kalleilv@gmail.com
          message: "format repository data"
          add: "data"
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}